### ISSUE TITLE
chsh password prompt on passwordless account

### ISSUE THREAD

**Issue by cruscio** [aaronkjones/noobs-term#12]
The install fails on Linux (Ubuntu Server 18.04) when run as a passwordless user. `chsh` prompts for a password regardless. In my case it's an Azure Linux VM provisioned with an SSH key.  

Fwiw, this change to [nobs-term.sh](https://github.com/aaronkjones/noobs-term/blob/36c6c9cb0afeaca1ca33f443d1c27562c7d0dd1c/noobs-term.sh#L170) enabled me to complete the install:

    diff noobs-term.sh noobs-term-sudo-chsh.sh
    171c171
    <               chsh -s "$(which zsh)"
    ---
    >               sudo chsh -s "$(which zsh)" `whoami`

**Comment by aaronkjones** [comment]
Thanks, @cruscio. I tested that change in a VM and I looks like that worked.
