### ISSUE TITLE
Not able to scroll (Figured it out)

### ISSUE THREAD

**Issue by josephhyatt** [aaronkjones/noobs-term#27]
I love the terminal configuration but I can't scroll to see previous terminal output. The scrool bar looks like a solid bar. In the terminal preferences it says I can scroll up to 100,000 lines. When I use the mouse wheel to scroll (like I did before) it just cycles through previous commands.  Any tips on how to fix this would be greatly appriacted. Thank you. Im using Ubuntu 18.04 with the stock terminal. I attached a screenshot.
![01-22-19 04 18](https://user-images.githubusercontent.com/22139956/51574131-6bc14500-1e61-11e9-9043-f4377c728929.png)

**Comment by josephhyatt** [comment]
Stupid me. Control - a. Sorry about that.

**Comment by aaronkjones** [comment]
@josephhyatt Yeah, that's the ticket. If you want to enable mouse support (and not have to press <kbd>Ctrl</kbd>+<kbd>[</kbd>) do this...

echo "setw -g mouse on" >> ~/.tmux.conf

then, <kbd>Ctrl</kbd>+<kbd>I</kbd>

**Comment by josephhyatt** [comment]
Thank you!
You're a gentleman and a scholar.
