### ISSUE TITLE
[Bugs/Not installed] Things I noticed.

### ISSUE THREAD

**Issue by Lzok** [aaronkjones/noobs-term#30]
**EDIT2 [SOLUTION]:** I had a ppa repository with errors and for some reason that breaks this installation script. I deleted it, uninstalled noob-term and installed it again and it worked perfectly. Awesome. 
So I think you can close the issue Aaron.

Hi Aron. For first let me tell you that I like so much your initiative to collect the tools with the beautiful Nord theme.

I came across some problems/things not installed after run the installing script (worth to mention that I didn't receive error messages during the instalation).

1. First thing I noticed was the nord theme for gnome was not installed, I had to install it by hand.
2. Tmux nord was not installed.
3. Zsh spaceship theme was not installed, I had to install it manually:
![Screenshot from 2019-05-11 15-12-21](https://user-images.githubusercontent.com/45211582/57574716-127b2280-740c-11e9-8dc3-8d376b81f512.png)
4. When nvim was installed, the `nvim` folder under `.local/share/` had root as the owner so when I wanted to run vim or nvim, it throwed errors. I solved it by changing that with chmod.
5. The entire .dotfiles folder was not installed (this is weird).

I tried to run twice but nothing. What do you suggest to try? Here are the installation log process and info of my system (under virtual box)

```bash
ubuntuvm% sh -c "$(wget -q https://raw.githubusercontent.com/aaronkjones/noobs-term/master/noobs-term.sh -O -)" 
Current platform: Linux
Current distribution version: 19.04
Current distribution: Ubuntu

/usr/bin/nvim

Installing dependencies...
[sudo] password for lean: \

# And that was all
```

![Screenshot from 2019-05-11 16-23-30](https://user-images.githubusercontent.com/45211582/57574792-8a961800-740d-11e9-8c5b-75c41bda7a7b.png)

If I can contribute to you and this project with something I'll glad to.

EDIT1: If I manually clone your dotfiles it seems to fix the tmux and zsh color configs.

**Comment by Lzok** [comment]
Now, I installed it on my Mac and everything seems to work ok except vim (it has the Nord theme applied). It looks ok but for some reason there is no a `.vimrc` file.

**Comment by Lzok** [comment]
This is just a question, do we need to specify all our configs in out init.vim? I mean, noob-term does not come with custom configs like remap leader key, set shortcuts for the plugins i.e toggle nerdtree, etc.

**Comment by aaronkjones** [comment]
Yeah you can add them in `init.vim` or what I like to do is modularize them like:

In `init.vim` add:
`source ~/.config/nvim/general.vimrc`
`source ~/.config/nvim/plugins.vimrc`
`source ~/.config/nvim/keybindings.vimrc`

Is that what you mean?

**Comment by Lzok** [comment]
Sorry for the delay, hard week.
Yes exactly that. I thought first that noobs-term comes with some default customs itself. 

I have one last question, for example, I am using one tab in iTerm with 3 tmux panes and when I want to create a new iTerm tab, that initializes the same 3 panes as the previous tab instead of a clean one. I can fix that with Tmux sessions, right?

Cheers!

**Comment by aaronkjones** [comment]
The reason that is happening is due to this block in `.zshrc`:

```
if [ -z "$TMUX" ] # When zsh is started attach to current tmux session or create a new one
then
    tmux attach -t TMUX || tmux new -s TMUX
fi
```

You can...

1. Remove that block and create/delete tmux sessions manually
2. Use tmux's built in tabbing <kbd>Control</kbd>+<kbd>a</kbd> then <kbd>c</kbd>

**Comment by Lzok** [comment]
@aaronkjones Thanks for the info.
Maybe in the future, the script could support fails and rollback instead of installing half of the things. But the job you did is awesome, I love the Nord palette. 

I'm closing the issue. Have a good day.
