### ISSUE TITLE
installer automatically assume iterm exists on macos

### ISSUE THREAD

**Issue by yursky** [aaronkjones/noobs-term#31]
When running the installer through something other than iterm it fails.

```
Installing Nord theme for iTerm...
No application knows how to open /var/folders/lr/t6prj1tx7w91pcxkf4z88g8w0000gn/T/tmp.LiYaxbLO/Nord.itermcolors.
```

Should change https://github.com/aaronkjones/noobs-term/blob/4b61667f52fae9f23733209a3dc6426c269dea80/noobs-term.sh#L267 to be safer

**Comment by aaronkjones** [comment]
Thanks, I added a check for iTerm.app.
