### ISSUE TITLE
Cannot complete install on Windows 10

### ISSUE THREAD

**Issue by jude-o** [aaronkjones/noobs-term#32]
Love the idea here - but I cannot complete the install on my Windows 10 machine. I was able to complete every step in the install guide except

> 7. Set shell to wsl.exe
> In Hyper: `chsh -s $(which zsh)`

The shell returns 
```
chsh: option requires an argument -- 's'
Usage: chsh [options] [LOGIN]
```
I *was* able to set the shell in the settings to the wsl.exe - does this accomplish the same thing?

Further, if I run my Ubuntu image in windows, I can use git commands, but if i try to run git in Hyper + noobs it says command not found. 

Have I crossed some wire along the way?

**Comment by aaronkjones** [comment]
chsh may have failed because `$(which zsh)` returned nothing. If you run `which zsh` does it return anything?

I haven't run this in Windows in a while, I'll give it a run through and see what happens.

**Comment by jude-o** [comment]
```which zsh``` returns nothing, the prompt just reloads. At what point in the install should zsh be installed?

**Comment by aaronkjones** [comment]
Can you include your hyper config?

Do you have this entry?
`shell: 'C:\\Windows\\System32\\wsl.exe',`

**Comment by jude-o** [comment]
I did get it set - but as I was typing out my reply, I realized it was almost like it was hooked into a different shell. I realized I _also_ have Kali Linux installed, so when I removed it and restarted Hyper, noobs is working!

Thanks for your help!
