### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by aaronkjones** [aaronkjones/noobs-term#6]
With ConEmu/Hyper and Windows Subsystem for Linux (WSL) this should work.

References:
* https://github.com/powerline/fonts
* https://medium.com/@patoncrispy/oh-my-windows-4a8aa0a276db

**Comment by brianjking** [comment]
@aaronkjones Have you considered [Scoop](https://github.com/lukesampson/scoop) instead of Chocolatey?

Here's a comparison between the two from the [Scoop Wiki](https://github.com/lukesampson/scoop/wiki/Chocolatey-Comparison). Here's some [other pertinent info as well](https://github.com/lukesampson/scoop/wiki/How-is-Scoop-different-to-Cygwin-and-MSYS%3F).

Thanks!

**Comment by aaronkjones** [comment]
@brianjking Thanks for the suggestion. I will check it out. I haven't been a Windows user in quite a while, so my knowledge on what tools are available is dated. Thanks again.

**Comment by brianjking** [comment]
@aaronkjones -- Not a problem, thank you! I really hope you might opt for Scoop over Chocolatey for the Windows support.

I know the feeling about the Windows tools as I'm actually moving away from Mac and more towards Windows 10 & Linux. 

I'm happy to help test this and have tagged @lukesampson (creator of Scoop) here as perhaps he can weigh in on any integrations. He also has a tool named [Pshazz](https://github.com/lukesampson/pshazz) for customizing Powershell inspirted by Oh-My-Zsh.

Thanks!

**Comment by aaronkjones** [comment]
Thanks @brianjking 
On first glance it looks like Scoop does not have a bucket for Hyper by default.

Hyper is in the [scoop-extras](https://github.com/lukesampson/scoop-extras).

So I think this adds another step to installing Hyper.

Also, the Hyper install instructions reference Chocolatey.

I will continue to look into Scoop though.

**Comment by aaronkjones** [comment]
@brianjking, I think this is a worthy replacement to Chocolatey. I will rewrite the steps in README.md. Thanks.

**Comment by brianjking** [comment]
@aaronkjones Fantastic, thanks! Let me know how I can help out.
