### ISSUE TITLE
Failing to add repo on Ubuntu Cosmic

### ISSUE THREAD

**Issue by ghost** [aaronkjones/noobs-term#7]
`E: The repository 'http://ppa.launchpad.net/neovim-ppa/stable/ubuntu cosmic Release' does not have a Release file.
`

This can be avoided by checking bin for neovim if adding the repository is not possible.

**Comment by aaronkjones** [comment]
[Added check for nvim](https://github.com/aaronkjones/noobs-term/commit/e4febb0bb11aff683a1d9ef43311a2aeb6cbba43)
