### ISSUE TITLE
Uninstall or toggle on/off

### ISSUE THREAD

**Issue by notDavid** [aaronkjones/noobs-term#9]
Hi there,

I haven't tried this yet, but before i nuke my settings ;-) is there an easy way to revert back to "pre-installed"?
Might be a good idea to add that to the README.md? There's an *install* section, but no *uninstall* section.

Thank you!

**Comment by aaronkjones** [comment]
@notDavid 
You're right. The documentation is lacking. The script will detect existing files and move them to `.backup` (e.g. .zshrc --> .zshrc.backup). You can also follow the [Demo](https://github.com/aaronkjones/noobs-term#demo) section.

I will update the documentation as well.

**Comment by notDavid** [comment]
👍

Also perhaps include how to set the shell back to the default in macOS.

**Comment by aaronkjones** [comment]
@notDavid 
Uninstall script added, including ability to change shell back to Bash.
